# Generated by Django 3.2.8 on 2021-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='Class_rating',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='c_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_The_sorting',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='manager',
            field=models.CharField(default=None, max_length=66),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
