# Generated by Django 3.2.8 on 2021-11-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211126_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.student'),
        ),
    ]
