# Generated by Django 3.2.8 on 2021-11-27 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_classroom_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursera_name', models.CharField(default=None, max_length=8)),
                ('coursera_type', models.CharField(default=None, max_length=8)),
                ('coursera_teacher', models.CharField(default=None, max_length=12)),
                ('credit', models.IntegerField(default=5)),
                ('coursera_comment', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'coursera',
                'verbose_name_plural': 'coursera',
                'db_table': 'db_coursera',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('is_qualified', models.BooleanField(default=False)),
                ('belong_student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='belong_student', to='student.student')),
                ('coursera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_coursera', to='student.coursera')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'score',
                'db_table': 'db_score',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default=None, max_length=255)),
                ('coursera_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profess_name', to='student.coursera')),
            ],
            options={
                'verbose_name': 'professional',
                'verbose_name_plural': 'professional',
                'db_table': 'db_professional',
            },
        ),
        migrations.AddField(
            model_name='coursera',
            name='probelong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursera_name', to='student.professional'),
        ),
    ]
