# Generated by Django 3.2.8 on 2021-11-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20211127_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursera',
            name='coursera_type',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='coursera_belong',
        ),
        migrations.AlterField(
            model_name='coursera',
            name='coursera_teacher',
            field=models.CharField(default=None, max_length=55),
        ),
    ]
