# Generated by Django 3.2.8 on 2021-11-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_coursera_be_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='header',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='studentManagementSystem/static/headers'),
        ),
    ]
