# Generated by Django 3.2.8 on 2021-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idCart',
            field=models.CharField(default=None, max_length=99),
        ),
    ]
