# Generated by Django 3.2.8 on 2021-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursera',
            name='coursera_comment',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
