# Generated by Django 3.2.8 on 2021-11-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_coursera_coursera_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
