# Generated by Django 3.2.8 on 2021-11-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_classroom_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursera',
            name='is_compulsory',
            field=models.BooleanField(default=True),
        ),
    ]
