# Generated by Django 3.2.8 on 2021-11-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_coursera_is_compulsory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursera',
            old_name='be_pr',
            new_name='be_prs',
        ),
    ]
