# Generated by Django 3.2.8 on 2021-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_coursera_be_prs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name': 'departments',
                'verbose_name_plural': 'departments',
                'db_table': 'db_depart',
            },
        ),
    ]
