# Generated by Django 3.2.8 on 2021-11-29 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursera',
            name='be_prs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='be_pr_for', to='student.departments'),
        ),
    ]
