# Generated by Django 3.2.8 on 2021-11-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_coursera_be_prs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursera',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
