# Generated by Django 3.2.8 on 2021-11-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_thesorting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_The_sorting',
        ),
    ]
