# Generated by Django 3.2.8 on 2021-11-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_remove_classroom_class_the_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_The_sorting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classSorting', to='student.thesorting'),
        ),
    ]
