# Generated by Django 3.2.7 on 2021-11-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nicknameuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nicknameUser',
            new_name='nickname',
        ),
    ]
